"""schemas/diligence_models.py — RedFlagAnalysis, SkillGapReport, CodeChallenge.

Tier 2 DueDiligenceSuite (ParallelAgent) produces all three in parallel:
  4b RedFlagDetectorAgent  → RedFlagAnalysis
  4c SkillGapAgent + E2B   → SkillGapReport + CodeChallenge
"""

from __future__ import annotations

import enum
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field, model_validator


class RedFlagSeverity(str, enum.Enum):
    CRITICAL = "CRITICAL"   # Immediate SKIP regardless of score
    HIGH = "HIGH"           # Strong signal to pass
    MEDIUM = "MEDIUM"       # Worth noting, not disqualifying
    LOW = "LOW"             # Minor concern


class RedFlag(BaseModel):
    """A single detected red flag."""

    category: str = Field(
        ...,
        description="ghost_job | toxic_culture | unrealistic_skills | agency_disguise | stale_listing | other",
    )
    severity: RedFlagSeverity
    evidence: str = Field(..., min_length=10, description="Specific evidence found (URL, quote, etc.)")
    description: str = Field(..., min_length=20)


class RedFlagAnalysis(BaseModel):
    """Output from RedFlagDetectorAgent (Tier 2, ParallelAgent sub-agent 4b)."""

    model_config = {"str_strip_whitespace": True}

    job_id: str
    flags: list[RedFlag] = Field(default_factory=list)
    ghost_job_probability: float = Field(
        ..., ge=0.0, le=1.0,
        description="Estimated probability this is a ghost/evergreen job (>60 days active)"
    )
    glassdoor_toxicity_score: float | None = Field(
        None, ge=0.0, le=1.0,
        description="Normalized toxicity score from Glassdoor scrape if available"
    )
    has_critical_flags: bool = False
    overall_recommendation: str = Field(
        ...,
        description="PROCEED | CAUTION | AVOID — final recommendation based on flags",
    )
    analyzed_at: datetime = Field(default_factory=datetime.utcnow)

    @model_validator(mode="after")
    def sync_critical_flags(self) -> "RedFlagAnalysis":
        self.has_critical_flags = any(f.severity == RedFlagSeverity.CRITICAL for f in self.flags)
        return self


class SkillGap(BaseModel):
    """A single skill gap identified between job requirements and user resume."""

    skill: str
    is_blocking: bool = Field(
        ...,
        description="True = required skill the user doesn't have. False = nice-to-have gap.",
    )
    proficiency_required: str | None = Field(
        None, description="e.g. '3+ years production experience', 'familiarity', etc."
    )
    learning_path: str | None = Field(
        None,
        max_length=300,
        description="Suggested resource / approach to close this gap (for non-blocking)",
    )


class CodeChallenge(BaseModel):
    """E2B sandbox result for a blocking skill gap practice challenge."""

    skill: str
    challenge_description: str = Field(..., min_length=30)
    generated_code: str = Field(..., description="Python code generated by SkillGapAgent")
    sandbox_stdout: str = Field(default="", max_length=2000)
    sandbox_stderr: str = Field(default="", max_length=500)
    execution_success: bool
    execution_time_ms: int = Field(..., ge=0)
    sandbox_id: str = Field(..., description="E2B sandbox ID for audit trail")


class SkillGapReport(BaseModel):
    """Output from SkillGapAgent (Tier 2, ParallelAgent sub-agent 4c)."""

    model_config = {"str_strip_whitespace": True}

    job_id: str
    user_id: str
    gaps: list[SkillGap] = Field(default_factory=list)
    blocking_gap_count: int = 0
    learnable_gap_count: int = 0
    code_challenges: list[CodeChallenge] = Field(
        default_factory=list,
        description="E2B-executed challenges for each blocking gap",
    )
    overall_readiness: str = Field(
        ...,
        description="READY | MINOR_GAPS | SIGNIFICANT_GAPS | NOT_QUALIFIED",
    )
    analyzed_at: datetime = Field(default_factory=datetime.utcnow)

    @model_validator(mode="after")
    def compute_gap_counts(self) -> "SkillGapReport":
        self.blocking_gap_count = sum(1 for g in self.gaps if g.is_blocking)
        self.learnable_gap_count = sum(1 for g in self.gaps if not g.is_blocking)
        return self
